[workspace]
members = ["operator/crates/operator/"
]

resolver = "2"

[workspace.package]
version = "0.0.1-alpha"
edition = "2021"
authors = ["Eigen Layer contributors"]
rust-version = "1.76"
repository = "https://github.com/Layr-Labs/hello-world-avs"
homepage = ""
license-file = "LICENSE"


[workspace.lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"
rust.unused_must_use = "deny"
rust.rust_2018_idioms = "deny"
rustdoc.all = "warn"


[workspace.dependencies]

hello-world-avs-operator = {path = "operator/crates/operator"}

#alloy
alloy-chains = "0.1.15"
alloy-primitives = "0.7.2"
alloy-dyn-abi = "0.7.2"
alloy-sol-types = "0.7.2"
alloy-rlp = "0.3.4"
alloy-trie = "0.3.1"
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-rpc-types-anvil = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-rpc-types-trace = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-rpc-types-engine = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-genesis = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-node-bindings = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-provider = { git = "https://github.com/alloy-rs/alloy", rev = "af788af", default-features = false, features = [
    "reqwest","ws"
] }
alloy-transport-http = {git = "https://github.com/alloy-rs/alloy", rev = "af788af"}
alloy-eips = { git = "https://github.com/alloy-rs/alloy", default-features = false, rev = "af788af" }
alloy-signer = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-signer-wallet = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-network = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-consensus = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-contract = {git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-transport =  {git = "https://github.com/alloy-rs/alloy", rev = "af788af"}
alloy-transport-ws = {git = "https://github.com/alloy-rs/alloy", rev = "af788af"}
alloy-rpc-client = {git = "https://github.com/alloy-rs/alloy", rev = "af788af"}